#!/bin/bash
#/* *-* mode: sh-mode *-* */ #bash syntax highlighting in emacs

EXCLUDE=('Porte-Agel_2000') #cases to exclude (array of strings

#get all samples
echo -n "getting list of samples..."
SAMPLES=`find . ! -name \*runSamples\* ! -name .\* -maxdepth 1 2>/dev/null | cut -f2 -d'/'`
SAMPLES=($SAMPLES)
echo "done."

#get rid of excluded cases
if [ ! -z "$EXCLUDE" ];then
    i=0
    for s in "${SAMPLES[@]}";do
	for e in "${EXCLUDE[@]}";do
	    if [ "$e" != "$s" ];then
		CASES[$i]="$s"
		i=$((i+1))
	    fi
	done
    done
fi

#looping through cases
for s in "${CASES[@]}";do

    echo "running $s..."
    cd $s

    echo -n "initlializing..."
    if [ ! -f 'init.m' ];then
	echo "failed."
	echo "init.m does not exist in $s."
	exit 1
    fi
    rm -f ../../input/*.ini ../../LESinputs.txt
    matlab -nodesktop -nosplash < init.m &> /dev/null
    if [[ ! -e '../../input/vel.ini' ]] || [[ ! -e '../../input/LESinputs.txt' ]];then
	echo "failed."
	echo "input creation unsuccessful."
	exit 1
    fi


    cd ..

done

exit 0